In [1]:
# Import numpy
import numpy as np

## Numpy Datatypes and attributes

In [2]:
# Create numpy array
a1= np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2= np.array([[1.0, 2, 3],
             [4, 5 , 6.0]])

a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
a3 = np.array([[[1, 2, 3],
               [4, 5 ,6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1

array([1, 2, 3])

In [7]:
a1.shape

(3,)

In [8]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
a2.shape

(2, 3)

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a3.shape

(2, 3, 3)

In [12]:
# to check the number of dimensions
a1.ndim, a2.ndim , a3.ndim

(1, 2, 3)

In [13]:
a1

array([1, 2, 3])

In [14]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
# Size of a numpy array : The size of an array is the number of elements inside the array
a1.size

3

In [17]:
a2.size

6

In [18]:
a3.size

18

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
# Create a PandasDaframe from a numpy array
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
# Import pandas
import pandas as pd

In [22]:
df= pd.DataFrame(a2)

df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

## 2 . Creating Arrays

In [23]:
sample_array= np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [24]:
sample_array.dtype

dtype('int64')

In [25]:
ones= np.ones(shape= (2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
ones_1= np.ones(shape= (3, 3), dtype="int")

ones_1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
ones_1.dtype

dtype('int64')

In [29]:
type(ones)

numpy.ndarray

In [30]:
zeros= np.zeros(shape= (3, 2), dtype="int")

zeros

array([[0, 0],
       [0, 0],
       [0, 0]])

In [31]:
zeros.dtype

dtype('int64')

In [32]:
zeros.size

6

In [33]:
type(zeros)

numpy.ndarray

In [34]:
range_array= np.arange(0, 13, 3)

range_array

array([ 0,  3,  6,  9, 12])

In [35]:
range_array.shape

(5,)

In [36]:
range_array.size

5

In [37]:
random_array= np.random.randint(0, 10, size= (2, 3))
random_array

array([[8, 5, 1],
       [0, 9, 5]])

In [38]:
random_array.shape

(2, 3)

In [39]:
random_array.size

6

In [40]:
random_array_2= np.random.random(size= (4, 4))
random_array_2

array([[0.64720118, 0.33335843, 0.57360516, 0.23749579],
       [0.07724301, 0.52444548, 0.74482835, 0.65928796],
       [0.32809331, 0.71690672, 0.06035466, 0.50679879],
       [0.38985569, 0.68229021, 0.7698337 , 0.95389055]])

In [41]:
# create another random array
random_array_3= np.random.rand(5, 3)

random_array_3

array([[0.55413097, 0.78400525, 0.8969163 ],
       [0.09950825, 0.82848647, 0.82861627],
       [0.51313204, 0.48398147, 0.44730115],
       [0.64941233, 0.7146353 , 0.88653488],
       [0.54424795, 0.96573493, 0.21897826]])

In [42]:
# set random  seed
np.random.seed(42)

random_array_4 = np.random.random(size= (3, 2))
random_array_4

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [43]:
np.random.seed(42)

random_array_5 = np.random.randint(0, 10, size=(2, 3))
random_array_5

array([[6, 3, 7],
       [4, 6, 9]])

In [44]:
random_array_5.shape

(2, 3)

## Viewing array and matrices

In [45]:
random_array= np.random.randint(0, 10, size=(3, 2))
random_array

array([[2, 6],
       [7, 4],
       [3, 7]])

In [46]:
np.unique(random_array)

array([2, 3, 4, 6, 7])

In [47]:
a1

array([1, 2, 3])

In [48]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [50]:
# Get the zero index of a1
a1[0]

1

In [51]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
a2[0]

array([1., 2., 3.])

In [53]:
a2[1]

array([4., 5., 6.])

In [54]:
# Let use slicing on our a2
a2[0][1]

2.0

In [55]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [56]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a3.shape

(2, 3, 3)

In [58]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [59]:
a3[0][1][0]

4

In [60]:
random_array_6 = np.random.randint(10, size= (2, 3, 4 , 5))
random_array_6

array([[[[7, 2, 5, 4, 1],
         [7, 5, 1, 4, 0],
         [9, 5, 8, 0, 9],
         [2, 6, 3, 8, 2]],

        [[4, 2, 6, 4, 8],
         [6, 1, 3, 8, 1],
         [9, 8, 9, 4, 1],
         [3, 6, 7, 2, 0]],

        [[3, 1, 7, 3, 1],
         [5, 5, 9, 3, 5],
         [1, 9, 1, 9, 3],
         [7, 6, 8, 7, 4]]],


       [[[1, 4, 7, 9, 8],
         [8, 0, 8, 6, 8],
         [7, 0, 7, 7, 2],
         [0, 7, 2, 2, 0]],

        [[4, 9, 6, 9, 8],
         [6, 8, 7, 1, 0],
         [6, 6, 7, 4, 2],
         [7, 5, 2, 0, 2]],

        [[4, 2, 0, 4, 9],
         [6, 6, 8, 9, 9],
         [2, 6, 0, 3, 3],
         [4, 6, 6, 3, 6]]]])

In [61]:
random_array_6.shape

(2, 3, 4, 5)

In [62]:
random_array_6.ndim

4

In [63]:
random_array_6[: , :, :, :4]

array([[[[7, 2, 5, 4],
         [7, 5, 1, 4],
         [9, 5, 8, 0],
         [2, 6, 3, 8]],

        [[4, 2, 6, 4],
         [6, 1, 3, 8],
         [9, 8, 9, 4],
         [3, 6, 7, 2]],

        [[3, 1, 7, 3],
         [5, 5, 9, 3],
         [1, 9, 1, 9],
         [7, 6, 8, 7]]],


       [[[1, 4, 7, 9],
         [8, 0, 8, 6],
         [7, 0, 7, 7],
         [0, 7, 2, 2]],

        [[4, 9, 6, 9],
         [6, 8, 7, 1],
         [6, 6, 7, 4],
         [7, 5, 2, 0]],

        [[4, 2, 0, 4],
         [6, 6, 8, 9],
         [2, 6, 0, 3],
         [4, 6, 6, 3]]]])

## Manipulating arrays and metrices

### Arithmetics

In [84]:
a1

array([1, 2, 3])

In [85]:
ones= np.ones(3)
ones

array([1., 1., 1.])

In [86]:
# Let add a1 and ones
a1 + ones

array([2., 3., 4.])

In [87]:
# let subtract
a1 - ones

array([0., 1., 2.])

In [88]:
# Let multiplt a1 and ones
a1 * ones

array([1., 2., 3.])

In [89]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [91]:
a1

array([1, 2, 3])

In [90]:
a1 * a2

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [92]:
# let divide a1 and ones
a1 / ones

array([1., 2., 3.])

In [93]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [94]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [95]:
np.square(a1)

array([1, 4, 9])

In [96]:
np.add(a1, ones)

array([2., 3., 4.])

In [97]:
a1 + ones

array([2., 3., 4.])

In [99]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [98]:
# Let try dividion
a2 / 2


array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [101]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [102]:
# to get the log 
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation= performing the same operation on a number of things

In [115]:
# Crate a python list
py_list = [1, 2 , 3]
py_list

[1, 2, 3]

In [116]:
sum(py_list)

6

In [117]:
a1

array([1, 2, 3])

In [118]:
np.sum(a1)

6

In [119]:
# Creating a mssive array
massive_array = np.random.random(100000)
massive_array

array([0.07384143, 0.95700406, 0.48999767, ..., 0.040752  , 0.80748064,
       0.74563087])

In [120]:
massive_array[:100]

array([0.07384143, 0.95700406, 0.48999767, 0.32485629, 0.92904918,
       0.43865477, 0.00554055, 0.56107373, 0.08910917, 0.98473212,
       0.90985851, 0.7505307 , 0.63411977, 0.04371908, 0.22501786,
       0.42121228, 0.77659378, 0.14019329, 0.75455037, 0.59833069,
       0.4915513 , 0.92082889, 0.66153708, 0.27190019, 0.46970747,
       0.6586628 , 0.0929167 , 0.14749753, 0.92684342, 0.26689737,
       0.36113996, 0.11955085, 0.19223815, 0.10367894, 0.75723824,
       0.55225335, 0.30063565, 0.26519431, 0.03533577, 0.56395819,
       0.21106442, 0.19858793, 0.82090596, 0.09495697, 0.70117325,
       0.24775504, 0.68566714, 0.10194738, 0.53185822, 0.45540042,
       0.46077018, 0.2199763 , 0.13847759, 0.80796243, 0.16981468,
       0.43472647, 0.03219549, 0.17693276, 0.13656716, 0.69239668,
       0.76980986, 0.8649838 , 0.03968303, 0.88092663, 0.32969307,
       0.90435173, 0.41503066, 0.01165419, 0.50316165, 0.59704758,
       0.59808708, 0.93516959, 0.42707727, 0.48222916, 0.99646

In [121]:
# Sum our massive array
%timeit sum(massive_array) # Python's sum
%timeit np.sum(massive_array) # numpy sum

8.32 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
45.7 µs ± 356 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [122]:
8320/ 45.7

182.05689277899342

In [123]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [125]:
np.mean(a2)

3.5

In [126]:
np.max(a2)

6.0

In [127]:
np.min(a2)

1.0

In [128]:
np.std(a2)

1.707825127659933

In [129]:
np.var(a2)

2.9166666666666665

In [130]:
np.sqrt(np.var(a2))

1.707825127659933

## Reshaping and transposing of numpy arrays

In [131]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [132]:
a2.shape

(2, 3)

In [134]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [136]:
a3.shape


(2, 3, 3)

In [137]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [138]:
a1

array([1, 2, 3])

In [140]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [139]:
a1 * a2


array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [143]:
a2_reshaped= np.reshape(a2, (2, 3, 1))
a2_reshaped

array([[[1.],
        [2.],
        [3.]],

       [[4.],
        [5.],
        [6.]]])

In [144]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [146]:
a2_reshaped * a3

array([[[  1.,   2.,   3.],
        [  8.,  10.,  12.],
        [ 21.,  24.,  27.]],

       [[ 40.,  44.,  48.],
        [ 65.,  70.,  75.],
        [ 96., 102., 108.]]])

In [148]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [147]:
a2.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [149]:
a2.T.shape

(3, 2)

In [150]:
a2.shape

(2, 3)

In [151]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [152]:
a3.T.shape

(3, 3, 2)

In [153]:
a3.shape

(2, 3, 3)

### Dot product

In [154]:
# Let crete random array 
np.random.seed(42)

mat1= np.random.randint(10, size=(5, 3))
mat2= np.random.randint(10, size=(5, 3))

In [155]:
mat1

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [156]:
mat2

array([[4, 1, 7],
       [5, 1, 4],
       [0, 9, 5],
       [8, 0, 9],
       [2, 6, 3]])

In [158]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [159]:
mat1 * mat2

array([[24,  3, 49],
       [20,  6, 36],
       [ 0, 54, 35],
       [32,  0, 63],
       [14, 12, 15]])

In [161]:
b1= np.array([1, 2, 3])
b2= np.array([4, 5, 6])

b1* b2

array([ 4, 10, 18])

In [162]:
np.dot(mat1 , mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [163]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [168]:
mat1_tran= mat1.T
mat1_tran

array([[6, 4, 2, 4, 7],
       [3, 6, 6, 3, 2],
       [7, 9, 7, 7, 5]])

In [170]:
mat1_tran.shape, mat2.shape

((3, 5), (5, 3))

In [171]:
np.dot(mat1_tran, mat2)

array([[ 90,  70, 125],
       [ 70,  75, 108],
       [139, 109, 198]])

## Comparision Operator


In [172]:
a1

array([1, 2, 3])

In [173]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [174]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [176]:
bool_array = a1 >= a2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [178]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [180]:
a1> 2

array([False, False,  True])

In [181]:
a1 == a1

array([ True,  True,  True])

In [182]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting numpy array

In [183]:
random_array= np.random.randint(10, size= (3, 5))
random_array

array([[8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3],
       [8, 1, 9, 8, 9]])

In [184]:
random_array.shape

(3, 5)

In [185]:
np.sort(random_array)

array([[2, 2, 4, 6, 8],
       [1, 3, 4, 6, 8],
       [1, 8, 8, 9, 9]])

In [186]:
a1

array([1, 2, 3])

In [187]:
np.argmin(a1)

0

In [188]:
np.argmax(a1)

2